<?php
/**
 * MIT License
 * 
 * Copyright (c) 2021 Luiz Ricardo de Lima
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

 
class DAOException extends Exception
{
    public function __construct($message, $code = 0, Exception $previous = null) {
        parent::__construct($message, $code, $previous);
    }
}

abstract class DAO
{
    protected $dbh;
    protected $entity;
    protected $properties;
    protected $key;
    protected $keyIsAutogenerated;
    private $delMethod;
    private $deactivateProperty;
    private $driver;
    
    protected const DEL_METHOD = 'del-method';
    protected const DEL_METHOD_DELETE = 'del-method-delete';
    protected const DEL_METHOD_DEACTIVATE = 'del-method-deactivate';

    protected const DEACTIVATE_PROPERTY = 'deactivate-property';

    function __construct($dbh, $entity, $properties, $key = 'id', $keyIsAutogenerated = true, $configuration = null) {
        
        // Validation - The properties array must have the $key element set
        if(!isset($properties[$key]))
            throw new DAOException('The key property '.$key.' was not defined on $properties param.');

        $this->dbh = $dbh;
        $this->entity = $entity;
        $this->properties = $properties;
        $this->key = $key;
        $this->keyIsAutogenerated = $keyIsAutogenerated;
        $this->driver = $dbh->getAttribute(PDO::ATTR_DRIVER_NAME);

        // Loading default configuration
        $this->delMethod = self::DEL_METHOD_DELETE;
        $this->deactivateProperty = null;
        // Loading custom configuration, if set
        if ($configuration !== null && is_array($configuration))
        {
            foreach($configuration as $configurationKey => $configurationValue) switch ($configurationKey) 
            {
                case self::DEL_METHOD:
                    if (in_array($configurationValue, [self::DEL_METHOD_DELETE, self::DEL_METHOD_DEACTIVATE]))
                        $this->delMethod = $configurationValue;
                    else
                        throw new DAOException('Invalid DEL_METHOD specified on $configuration.');
                    break;
                case self::DEACTIVATE_PROPERTY:
                    if(isset($properties[$configurationValue]))
                        $this->deactivateProperty = $configurationValue;
                    else
                        throw new DAOException('DEACTIVATE_PROPERTY specified on $configuration is not set on $properties.');
                    break;
            }            
        }           
    }

    public function create($object) {
        if (!$this->keyIsAutogenerated && !isset($object[$this->key]))
            throw new DAOException('Missing key property '.$this->key.' on create. This property is not autogenerated.');
        
        $pos = 0;
        $names  = array();
        $types  = array();
        $values = array();
        $params = array();
        foreach ($this->properties as $propertyName => $propertyType) {
            // If keys are autogenerated, any input values for them will be ignored
            if ($propertyName == $this->key && $this->keyIsAutogenerated)
                continue;  
            if (isset($object[$propertyName])) {
                $names[$pos] = $this->escape($propertyName);
                $types[$pos] = $propertyType;
                $values[$pos] = $object[$propertyName];
                $params[$pos] = '?';
                $pos++;
            }
        }
        $query = 'INSERT INTO '.$this->escape($this->entity).' (';
        $query.= implode(', ', $names);
        $query.= ') VALUES (';
        $query.= implode(', ', $params);
        $query.= ')';

        $stmt = $this->dbh->prepare($query);
        for($i = 0; $i < $pos; $i++) {
            $stmt->bindValue($i+1, $values[$i], $types[$i]);
        }
        $stmt->execute();
        if ($this->keyIsAutogenerated)
            return $this->dbh->lastInsertId();
        else
            return $object[$this->key];
    }

    public function del($key) {
        switch ($this->delMethod) {
            case self::DEL_METHOD_DELETE:
                $stmt = $this->dbh->prepare(
                    'DELETE FROM '.$this->escape($this->entity).' WHERE '.$this->escape($this->key).' = ?');
                $stmt->bindValue(1, $key, $this->properties[$this->key]);
                $stmt->execute();
                return true;
                break;
            case self::DEL_METHOD_DEACTIVATE:
                $query = 'UPDATE '.$this->escape($this->entity);
                $query.= ' SET '.$this->escape($this->deactivateProperty).' = 0';
                $query.= ' WHERE '.$this->escape($this->key).' = ?';
                $stmt = $this->dbh->prepare($query);
                $stmt->bindValue(1, $key, $this->properties[$this->key]);
                $stmt->execute();
                return true;
                break;
        }
    }

    public function get($key) {
        $stmt = $this->dbh->prepare(
            'SELECT * FROM '.$this->escape($this->entity).' WHERE '.$this->escape($this->key).' = ?');
        $stmt->bindValue(1, $key, $this->properties[$this->key]);
        $stmt->execute();
        $result = $stmt->fetch(PDO::FETCH_ASSOC);
        return $result ? $result : null;
    }

    public function update($object) {
        if (!isset($object[$this->key]))
            throw new DAOException('Missing key property '.$this->key.' on update.');
        
        $pos = 0;
        $types  = array();
        $values = array();
        $params = array();
        foreach ($this->properties as $propertyName => $propertyType) {
            if ($propertyName == $this->key) continue;  
            if (isset($object[$propertyName])) {
                $types[$pos] = $propertyType;
                $values[$pos] = $object[$propertyName];
                $params[$pos] = $this->escape($propertyName).' = ?';
                $pos++;
            }
        }

        $query = 'UPDATE '.$this->escape($this->entity).' SET';
        $query.= implode(', ', $params);
        $query.= ' WHERE '.$this->escape($this->key).' = ?';

        $stmt = $this->dbh->prepare($query);
        for($i = 0; $i < $pos; $i++) {
            $stmt->bindValue($i+1, $values[$i], $types[$i]);
        }
        $stmt->bindValue($pos+1, $object[$this->key], $this->properties[$this->key]);
        $stmt->execute();
        return true;
    }

    /**
     *  When $filters are set and the Dao subclass deletes by deactivating, $deactivateProperty
     *  needs to be in the search parameters if only the not deleted entries need to be retrieved.
     *  If no parameters are passed ($filters == null), this function will retriver only the active
     *  (not deleted) items.
     * 
     *  $filters is an array of filter objects. This object need to have 3 keys: 'property',
     *  'operator' and 'value'. Example: [['property' => 'id', 'operator'=>'=', 'value' => '42']];
     * 
     *  Implemented operators: =, <, >, <=, >=, <>, LIKE
     */ 
    public function list($elementKeyAsArrayKey = true, $filters = null)
    {
        $query = 'SELECT * FROM '.$this->escape($this->entity);
        if ($filters === null && $this->delMethod == self::DEL_METHOD_DEACTIVATE) {
            $query .= ' WHERE '.$this->escape($this->deactivateProperty).' = 1';
        }

        $pos = 0;
        $filterQuery = array();
        $filterVariables = array();
        $filterTypes = array();
        if (is_array($filters)) foreach ($filters as $key => $filter) {
            if (!isset($filter['operator']))
                throw new DAOException('Operator not specified for filter in position '.$key.'.');
            else if (!in_array($filter['operator'], ['=','<','>','<=','>=','<>','LIKE']))
                throw new DAOException('Invalid or unimplemented operator '.$filter['operator'].' for filter in position '.$key.'.');
            else if (!isset($filter['property']))
                throw new DAOException('Missing \'property\' for filter in position '.$key.'.');
            else if(!isset($this->properties[$filter['property']]))
                throw new DAOException('The property '.$filter['property'].' for filter in position '.$key.' is not defined in the class.');
            else if (!isset($filter['value']))
                throw new DAOException('Missing \'value\' for filter in position '.$key.'.');
            else { // all good!
                $filterQuery[$pos] = $this->escape($filter['property']).' '.$filter['operator'].' ?';
                $filterVariables[$pos] = $filter['value'];
                $filterTypes[$pos] = $this->properties[$filter['property']];
                $pos++;
            }
        }

        if ($pos > 0) {
            $query.= ' WHERE '.implode(' AND ', $filterQuery);
        }

        $stmt = $this->dbh->prepare($query);

        if ($pos > 0) {    
            for($i = 0; $i < $pos; $i++) {
                $stmt->bindValue($i+1, $filterVariables[$i], $filterTypes[$i]);
            }
        }
        
        $stmt->execute();
        $result = array();
        while ($object = $stmt->fetch(PDO::FETCH_ASSOC)) {
            if($elementKeyAsArrayKey)
                $result[$object[$this->key]] = $object;
            else
                $result[] = $object;
        }
        return $result;
    }

    // TODO: IMPLEMENT FOR OTHER DRIVERS
    protected function escape($name) {
        switch ($this->driver) {
            case 'mysql':
                return "`$name`";
            default:
                return $name;
        }
    }
    
}